title: chilaxan's blog
email: chilaxan@gmail.com
description: This is my blog for all of my odd projects and interesting things I have learned
baseurl: "" 
url: "https://chilaxan.github.io"

remote_theme: jekyll/minima
plugins:
  - jekyll-feed

minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/chilaxan" }
    - { platform: twitter, user_url: "https://twitter.com/chilaxan1" }

show_excerpts: true
disqus:
  shortname: chilaxan-blog

author:
  name: Jordan Limor
  email: "chilaxan@gmail.com"
